name: setuapp
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for the application
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font
  cupertino_icons: ^1.0.8

  # State management and utility packages
  shared_preferences: ^2.5.3
  get: ^4.6.6
  http: ^1.2.2
  jwt_decoder: ^2.0.1

  # Animation packages
  flutter_animate: ^4.5.0
  lottie: ^3.1.0


  # Icon packages
  phosphor_flutter: ^2.1.0
  lucide_icons: ^0.257.0

  # UI component packages
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  card_swiper: ^3.0.1
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  video_player: ^2.10.0
  file_picker: ^10.2.0
  dropdown_button2: ^2.3.9

  # Styling and layout packages
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_screenutil: ^5.9.0
  confetti: ^0.8.0
  translator: ^1.0.3+1
  connectivity_plus: ^6.1.4
  google_translator: ^1.0.0
  share_plus: ^11.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package for Flutter
  flutter_lints: ^5.0.0

# Flutter-specific configuration
flutter:
  # Ensures Material Icons font is included
  uses-material-design: true

  # Example of adding assets (uncomment and modify as needed)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Example of adding custom fonts (uncomment and modify as needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
